enunciados:
	git web--browse www/index.html

server:
	@echo "Iniciando servidor..."
	python3 server.py

client: 
	@echo "Cliente conectado"
	python3 client.py

all:
	@echo "Compilacion / ejecucion del ejercicio"

clean:
	@echo "Limpiando..."
